on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Cache node modules
                uses: actions/cache@v3
                with:
                    path: ./node_modules
                    key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
            -   name: Install packages
                run: npm install
            -   name: Build Project
                run: npm run build:ci
            -   name: Upload build artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: deployment-build
                    path: |
                        dist
                        firebase.json
                        database.rules.json
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v4
                with:
                    name: deployment-build
            -   name: Deploy site
                uses: FirebaseExtended/action-hosting-deploy@v0
                with:
                    repoToken: ${{ secrets.GITHUB_TOKEN }}
                    firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DATE_IDEA_SCRAMBLER }}
                    channelId: live
                    projectId: date-idea-scrambler
            -   name: Deploy database rules
                uses: DuncanMcPherson/action-database-deploy@master
                with:
                    repoToken: ${{ secrets.FIREBASE_CI_TOKEN }}
                    firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DATE_IDEA_SCRAMBLER }}
                    projectId: date-idea-scrambler
#    test:
#        runs-on: ubuntu-latest
#    coverage-results:
#        runs-on: ubuntu-latest
#        needs: test
