name: Build, Test, and Deploy
'on': pull_request
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Cache node modules
                uses: actions/cache@v3
                with:
                    path: ./node_modules
                    key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
            -   name: Install Packages
                run: npm ci
            -   name: Build Project
                run: npm run build:ci
            -   name: Upload build artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: ci-build
                    path: dist
    deploy:
        needs: build
        if: never()
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Download artifacts
                uses: actions/download-artifact@v4
                with:
                    name: ci-build
    test:
        if: always()
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Cache Node Modules
                uses: actions/cache@v3
                with:
                    path: ./node_modules
                    key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
            -   name: Install packages
                run: npm ci
            -   name: Run Tests
                run: npm run test:ci
            -   name: Upload test results
                uses: actions/upload-artifact@v4
                with:
                    name: test-results
                    path: test-results
# TODO: upload test results
